# Generated by Django 4.1.5 on 2023-02-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('leoapp', '0002_alter_pricedynamic_tmp'),
    ]

    def blank_to_zero(apps, schema_editor):
        PriceDynamic = apps.get_model('leoapp', 'pricedynamic')

        for price_dynamic in PriceDynamic.objects.all():
            try:
                price_dynamic.tmp = int(price_dynamic.tmp)
            except:
                price_dynamic.tmp = -1

            price_dynamic.save()

    operations = [
        migrations.RunPython(blank_to_zero),
        migrations.AlterField(
            model_name='pricedynamic',
            name='tmp',
            field=models.IntegerField(verbose_name='delete me'),
        ),
    ]
