# Generated by Django 4.1.5 on 2023-02-02 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leoapp', '0003_alter_pricedynamic_tmp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricedynamic',
            name='tmp',
        ),
    ]
