# Generated by Django 4.1.5 on 2023-02-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leoapp', '0005_alter_items_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_url',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='items',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
