# Generated by Django 4.1.5 on 2023-02-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leoapp', '0006_alter_itemproperty_property_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedynamic',
            name='price_date',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
